'use strict';
const { faker } = require('@faker-js/faker');

const randomOrderCount = () => {
  return Math.round(Math.random() * 100);
};

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Items',
      [
        {
          name: 'Cooler Master MasterLiquid ML240R RGB',
          category_id: 9,
          price: 6500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/614fsCjOUAL.jpg',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel LGA 2066/2011-v3/2011/1200/1151/1150/1155/1366 and AMD AM4/AM3+/AM3/AM2+/AM2/FM2+/FM2/FM1',
            'Radiator Size': '240mm',
            'Fan Speed': '650 - 2000 RPM',
            'Noise Level': '6 - 30 dBA',
            'RGB Lighting': 'Yes',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'NVIDIA GeForce RTX 3080',
          category_id: 5,
          price: 135000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/nvidiageforcertx3080founderseditionmb3dmodel001.jpg',
          description: JSON.stringify({
            'GPU Architecture': 'NVIDIA Ampere',
            'Memory Size': '10 GB GDDR6X',
            'Memory Type': 'GDDR6X',
            'Max Resolution': '7680x4320',
            Interface: 'PCI Express 4.0',
            'Power Connectors': '2 x 8-pin',
            Dimensions: {
              length: 285,
              width: 112,
              height: 40,
            },
            'Recommended Power Supply': '750W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Avid Pro Tools Carbon',
          category_id: 10,
          price: 369990,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/71zAgopOqJL.jpg',
          description: JSON.stringify({
            Channels: '25',
            'Max Sample Rate': '192 kHz',
            Interface: 'Thunderbolt 3',
            'Bit Depth': '24-bit',
            'DAC (Digital-to-Analog Converter)': '24-bit/192 kHz',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Intel Core i5-10600K',
          category_id: 1,
          price: 15900,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/71JwR1kW3WS.jpg',
          description: JSON.stringify({
            'Socket Type': 'LGA 1200',
            'Cores/Threads': '6/12',
            'Base Clock Speed': '4.1 GHz',
            'Max Boost Clock Speed': '4.8 GHz',
            TDP: '125W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'AMD Radeon RX 6900 XT',
          category_id: 5,
          price: 130000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/579976-radeon-rx-6000xt-left-angle-1260x709_0.png.webp',
          description: JSON.stringify({
            'GPU Architecture': 'RDNA 2',
            'Memory Size': '16 GB GDDR6',
            'Memory Type': 'GDDR6',
            'Max Resolution': '7680x4320',
            Interface: 'PCI Express 4.0',
            'Power Connectors': '2 x 8-pin',
            Dimensions: {
              length: 267,
              width: 120,
              height: 40,
            },
            'Recommended Power Supply': '850W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'NVIDIA GeForce RTX 3070',
          category_id: 5,
          price: 90000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/geforce-rtx-3070-shop-630-d@2x.png',
          description: JSON.stringify({
            'GPU Architecture': 'NVIDIA Ampere',
            'Memory Size': '8 GB GDDR6',
            'Memory Type': 'GDDR6',
            'Max Resolution': '7680x4320',
            Interface: 'PCI Express 4.0',
            'Power Connectors': '1 x 12-pin',
            Dimensions: {
              length: 242,
              width: 112,
              height: 40,
            },
            'Recommended Power Supply': '650W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'AMD Radeon RX 6800 XT',
          category_id: 5,
          price: 95000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/AMDrx6800XT.webp',
          description: JSON.stringify({
            'GPU Architecture': 'RDNA 2',
            'Memory Size': '16 GB GDDR6',
            'Memory Type': 'GDDR6',
            'Max Resolution': '7680x4320',
            Interface: 'PCI Express 4.0',
            'Power Connectors': '2 x 8-pin',
            Dimensions: {
              length: 267,
              width: 120,
              height: 40,
            },
            'Recommended Power Supply': '750W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'NVIDIA GeForce RTX 3060 Ti',
          category_id: 5,
          price: 60000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/rtx3060ti.jpg',
          description: JSON.stringify({
            'GPU Architecture': 'NVIDIA Ampere',
            'Memory Size': '8 GB GDDR6',
            'Memory Type': 'GDDR6',
            'Max Resolution': '7680x4320',
            Interface: 'PCI Express 4.0',
            'Power Connectors': '1 x 12-pin',
            Dimensions: {
              length: 242,
              width: 112,
              height: 40,
            },
            'Recommended Power Supply': '600W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'AMD Radeon RX 6700 XT',
          category_id: 5,
          price: 48000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/amdRadeonRX6700XT.jpg',
          description: JSON.stringify({
            'GPU Architecture': 'RDNA 2',
            'Memory Size': '12 GB GDDR6',
            'Memory Type': 'GDDR6',
            'Max Resolution': '7680x4320',
            Interface: 'PCI Express 4.0',
            'Power Connectors': '1 x 8-pin',
            Dimensions: {
              length: 267,
              width: 120,
              height: 40,
            },
            'Recommended Power Supply': '650W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'NVIDIA GeForce RTX 2080 Ti',
          category_id: 5,
          price: 110000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/gfRTX2080TI.jpeg',
          description: JSON.stringify({
            'GPU Architecture': 'NVIDIA Turing',
            'Memory Size': '11 GB GDDR6',
            'Memory Type': 'GDDR6',
            'Max Resolution': '7680x4320',
            Interface: 'PCI Express 3.0',
            'Power Connectors': '2 x 8-pin',
            Dimensions: {
              length: 267,
              width: 120,
              height: 40,
            },
            'Recommended Power Supply': '650W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'AMD Radeon RX 5700 XT',
          category_id: 5,
          price: 40000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/amd-radeon-rx-5700-xt-review.jpg',
          description: JSON.stringify({
            'GPU Architecture': 'RDNA',
            'Memory Size': '8 GB GDDR6',
            'Memory Type': 'GDDR6',
            'Max Resolution': '7680x4320',
            Interface: 'PCI Express 4.0',
            'Power Connectors': '1 x 8-pin, 1 x 6-pin',
            Dimensions: {
              length: 270,
              width: 111,
              height: 40,
            },
            'Recommended Power Supply': '600W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'NVIDIA GeForce GTX 1660 Super',
          category_id: 5,
          price: 25000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/ngfGTX1660super.jpg',
          description: JSON.stringify({
            'GPU Architecture': 'NVIDIA Turing',
            'Memory Size': '6 GB GDDR6',
            'Memory Type': 'GDDR6',
            'Max Resolution': '7680x4320',
            Interface: 'PCI Express 3.0',
            'Power Connectors': '1 x 8-pin',
            Dimensions: {
              length: 228,
              width: 131,
              height: 41,
            },
            'Recommended Power Supply': '450W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'AMD Radeon RX 5600 XT',
          category_id: 5,
          price: 28000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/amdRadeonRx5600xt.jpg',
          description: JSON.stringify({
            'GPU Architecture': 'RDNA',
            'Memory Size': '6 GB GDDR6',
            'Memory Type': 'GDDR6',
            'Max Resolution': '7680x4320',
            Interface: 'PCI Express 4.0',
            'Power Connectors': '1 x 8-pin',
            Dimensions: {
              length: 270,
              width: 111,
              height: 40,
            },
            'Recommended Power Supply': '550W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'NVIDIA GeForce GTX 1650 Super',
          category_id: 5,
          price: 16000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/1650super.jpg',
          description: JSON.stringify({
            'GPU Architecture': 'NVIDIA Turing',
            'Memory Size': '4 GB GDDR6',
            'Memory Type': 'GDDR6',
            'Max Resolution': '7680x4320',
            Interface: 'PCI Express 3.0',
            'Power Connectors': '1 x 6-pin',
            Dimensions: {
              length: 171,
              width: 111,
              height: 39,
            },
            'Recommended Power Supply': '350W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'AMD Radeon RX 5500 XT',
          category_id: 5,
          price: 20000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/RX5500XT.jpg',
          description: JSON.stringify({
            'GPU Architecture': 'RDNA',
            'Memory Size': '8 GB GDDR6',
            'Memory Type': 'GDDR6',
            'Max Resolution': '7680x4320',
            Interface: 'PCI Express 4.0',
            'Power Connectors': '1 x 8-pin',
            Dimensions: {
              length: 247,
              width: 129,
              height: 42,
            },
            'Recommended Power Supply': '450W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'ASUS ROG Strix X570-E Gaming',
          category_id: 2,
          price: 24500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/StrixX570-EGamingImage_678x452.jpg',
          description: JSON.stringify({
            'Socket Type': 'AM4',
            'Form Factor': 'ATX',
            'Memory Type': 'DDR4',
            'Max Memory Size': '128 GB',
            'PCI Express Slots': '3 x16, 2 x1',
            'USB Ports': '12 x USB 3.2 Gen 2, 8 x USB 3.2 Gen 1',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'GIGABYTE X570 AORUS Elite',
          category_id: 2,
          price: 17500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/x570aorusElite.jpg',
          description: JSON.stringify({
            'Socket Type': 'AM4',
            'Form Factor': 'ATX',
            'Memory Type': 'DDR4',
            'Max Memory Size': '128 GB',
            'PCI Express Slots': '2 x16, 1 x4, 3 x1',
            'USB Ports': '8 x USB 3.2 Gen 2, 6 x USB 2.0',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'MSI MPG B550 Gaming Plus',
          category_id: 2,
          price: 12900,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/MSIMPGB550GamingPlus.jpg',
          description: JSON.stringify({
            'Socket Type': 'AM4',
            'Form Factor': 'ATX',
            'Memory Type': 'DDR4',
            'Max Memory Size': '128 GB',
            'PCI Express Slots': '2 x16, 3 x1',
            'USB Ports': '6 x USB 3.2 Gen 1, 6 x USB 2.0',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'ASRock B550M-ITX/ac',
          category_id: 2,
          price: 10900,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/ASRockB550M-ITX:ac.jpg',
          description: JSON.stringify({
            'Socket Type': 'AM4',
            'Form Factor': 'Mini-ITX',
            'Memory Type': 'DDR4',
            'Max Memory Size': '64 GB',
            'PCI Express Slots': '1 x16',
            'USB Ports': '6 x USB 3.2 Gen 1, 6 x USB 2.0',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'ASUS TUF Gaming B550-PLUS',
          category_id: 2,
          price: 13900,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/ASUSTUFGamingB550-PLUS.jpg',
          description: JSON.stringify({
            'Socket Type': 'AM4',
            'Form Factor': 'ATX',
            'Memory Type': 'DDR4',
            'Max Memory Size': '128 GB',
            'PCI Express Slots': '2 x16, 3 x1',
            'USB Ports': '6 x USB 3.2 Gen 2, 6 x USB 2.0',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'GIGABYTE B450 AORUS Elite',
          category_id: 2,
          price: 9900,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/GIGABYTEB450AORUSElite.jpg',
          description: JSON.stringify({
            'Socket Type': 'AM4',
            'Form Factor': 'ATX',
            'Memory Type': 'DDR4',
            'Max Memory Size': '64 GB',
            'PCI Express Slots': '1 x16, 1 x4, 2 x1',
            'USB Ports': '6 x USB 3.1 Gen 1, 8 x USB 2.0',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'ASRock B450M PRO4',
          category_id: 2,
          price: 8500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/ASRockB450MPRO4.jpg',
          description: JSON.stringify({
            'Socket Type': 'AM4',
            'Form Factor': 'Micro-ATX',
            'Memory Type': 'DDR4',
            'Max Memory Size': '64 GB',
            'PCI Express Slots': '1 x16, 1 x4, 1 x1',
            'USB Ports': '6 x USB 3.1 Gen 1, 8 x USB 2.0',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'MSI B450 TOMAHAWK MAX',
          category_id: 2,
          price: 9900,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/MSI-B450-Tomahawk-AM4-Motherboard-(5)_678x452.jpg',
          description: JSON.stringify({
            'Socket Type': 'AM4',
            'Form Factor': 'ATX',
            'Memory Type': 'DDR4',
            'Max Memory Size': '64 GB',
            'PCI Express Slots': '1 x16, 1 x4, 4 x1',
            'USB Ports': '6 x USB 3.2 Gen 1, 6 x USB 2.0',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'ASUS PRIME B450-PLUS',
          category_id: 2,
          price: 7900,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/materinskaya-plata-asus-prime-b450-plus-am4-1.jpg',
          description: JSON.stringify({
            'Socket Type': 'AM4',
            'Form Factor': 'ATX',
            'Memory Type': 'DDR4',
            'Max Memory Size': '64 GB',
            'PCI Express Slots': '1 x16, 2 x4, 3 x1',
            'USB Ports': '6 x USB 3.1 Gen 1, 8 x USB 2.0',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'GIGABYTE B365M DS3H',
          category_id: 2,
          price: 5900,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/GIGABYTEB365MDS3H.jpg',
          description: JSON.stringify({
            'Socket Type': 'LGA 1151',
            'Form Factor': 'Micro-ATX',
            'Memory Type': 'DDR4',
            'Max Memory Size': '64 GB',
            'PCI Express Slots': '1 x16, 2 x1',
            'USB Ports': '4 x USB 3.1 Gen 1, 8 x USB 2.0',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Intel Core i9-9900K',
          category_id: 1,
          price: 29900,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/IntelCorei9-9900K.jpg',
          description: JSON.stringify({
            'Socket Type': 'LGA 1151',
            'Cores/Threads': '8/16',
            'Base Clock Speed': '3.6 GHz',
            'Max Boost Clock Speed': '5.0 GHz',
            TDP: '95W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'AMD Ryzen 7 5800X',
          category_id: 1,
          price: 25900,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/AMDRyzen75800X.jpg',
          description: JSON.stringify({
            'Socket Type': 'AM4',
            'Cores/Threads': '8/16',
            'Base Clock Speed': '3.8 GHz',
            'Max Boost Clock Speed': '4.7 GHz',
            TDP: '105W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Intel Core i7-10700K',
          category_id: 1,
          price: 21900,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/IntelCorei7-10700K.jpg',
          description: JSON.stringify({
            'Socket Type': 'LGA 1200',
            'Cores/Threads': '8/16',
            'Base Clock Speed': '3.8 GHz',
            'Max Boost Clock Speed': '5.1 GHz',
            TDP: '125W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'AMD Ryzen 5 5600X',
          category_id: 1,
          price: 17900,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/protsessor_amd_ryzen_5_5600x_am4_box_1532802_1.jpg',
          description: JSON.stringify({
            'Socket Type': 'AM4',
            'Cores/Threads': '6/12',
            'Base Clock Speed': '3.7 GHz',
            'Max Boost Clock Speed': '4.6 GHz',
            TDP: '65W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Intel Core i5-11600K',
          category_id: 1,
          price: 16900,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/IntelCorei5-11600K.jpg',
          description: JSON.stringify({
            'Socket Type': 'LGA 1200',
            'Cores/Threads': '6/12',
            'Base Clock Speed': '3.9 GHz',
            'Max Boost Clock Speed': '4.9 GHz',
            TDP: '125W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'AMD Ryzen 9 5900X',
          category_id: 1,
          price: 38900,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/AMDRyzen95900X.jpg',
          description: JSON.stringify({
            'Socket Type': 'AM4',
            'Cores/Threads': '12/24',
            'Base Clock Speed': '3.7 GHz',
            'Max Boost Clock Speed': '4.8 GHz',
            TDP: '105W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Intel Core i7-11700K',
          category_id: 1,
          price: 24900,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/protsessor_intel_core_i7_11700k_lga1200_box_1692958_1.jpg',
          description: JSON.stringify({
            'Socket Type': 'LGA 1200',
            'Cores/Threads': '8/16',
            'Base Clock Speed': '3.6 GHz',
            'Max Boost Clock Speed': '5.0 GHz',
            TDP: '125W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'AMD Ryzen 7 3700X',
          category_id: 1,
          price: 19900,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/AMDRyzen73700X.png.webp',
          description: JSON.stringify({
            'Socket Type': 'AM4',
            'Cores/Threads': '8/16',
            'Base Clock Speed': '3.6 GHz',
            'Max Boost Clock Speed': '4.4 GHz',
            TDP: '65W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'AMD Ryzen 5 3600X',
          category_id: 1,
          price: 13900,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/AMDRyzen53600X.jpg',
          description: JSON.stringify({
            'Socket Type': 'AM4',
            'Cores/Threads': '6/12',
            'Base Clock Speed': '3.8 GHz',
            'Max Boost Clock Speed': '4.4 GHz',
            TDP: '95W',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Corsair Vengeance LPX 16GB (2 x 8GB) DDR4 3200MHz',
          category_id: 3,
          price: 7500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/CorsairVengeanceLPX.webp',
          description: JSON.stringify({
            Capacity: '16GB (2 x 8GB)',
            'Memory Type': 'DDR4',
            Speed: '3200MHz',
            'CAS Latency': '16',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'G.Skill Trident Z RGB 32GB (2 x 16GB) DDR4 3600MHz',
          category_id: 3,
          price: 10500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/GSkillTridentZRGB.png.webp',
          description: JSON.stringify({
            Capacity: '32GB (2 x 16GB)',
            'Memory Type': 'DDR4',
            Speed: '3600MHz',
            'CAS Latency': '18',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Crucial Ballistix 16GB (2 x 8GB) DDR4 3000MHz',
          category_id: 3,
          price: 6000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/CrucialBallistix.jpg',
          description: JSON.stringify({
            Capacity: '16GB (2 x 8GB)',
            'Memory Type': 'DDR4',
            Speed: '3000MHz',
            'CAS Latency': '15',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Kingston HyperX Fury RGB 16GB (2 x 8GB) DDR4 3200MHz',
          category_id: 3,
          price: 6500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/KingstonHyperXFuryRGB.jpg',
          description: JSON.stringify({
            Capacity: '16GB (2 x 8GB)',
            'Memory Type': 'DDR4',
            Speed: '3200MHz',
            'CAS Latency': '16',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Team T-Force Delta RGB 32GB (2 x 16GB) DDR4 3200MHz',
          category_id: 3,
          price: 8500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/TeamT-ForceDeltaRGB.jpg',
          description: JSON.stringify({
            Capacity: '32GB (2 x 16GB)',
            'Memory Type': 'DDR4',
            Speed: '3200MHz',
            'CAS Latency': '16',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Corsair Vengeance RGB Pro 32GB (2 x 16GB) DDR4 3600MHz',
          category_id: 3,
          price: 9500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/CorsairVengeanceRGBPro.webp',
          description: JSON.stringify({
            Capacity: '32GB (2 x 16GB)',
            'Memory Type': 'DDR4',
            Speed: '3600MHz',
            'CAS Latency': '18',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'G.Skill Ripjaws V 16GB (2 x 8GB) DDR4 3200MHz',
          category_id: 3,
          price: 7000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/operativnaya_pamyat_ddr4_g.skill_ripjaws_v_16gb_2x8gb_kit_3200mhz_cl16_1.35v_f4_3200c16d_16gvkb_classic_black_1137436_1.jpg',
          description: JSON.stringify({
            Capacity: '16GB (2 x 8GB)',
            'Memory Type': 'DDR4',
            Speed: '3200MHz',
            'CAS Latency': '16',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Crucial Ballistix MAX 32GB (2 x 16GB) DDR4 4000MHz',
          category_id: 3,
          price: 11000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/ballistix-blm2k16g40c18u4b-cl18-max-32gb-2x16gb-ddr4-4000mhz-ram-память.jpg',
          description: JSON.stringify({
            Capacity: '32GB (2 x 16GB)',
            'Memory Type': 'DDR4',
            Speed: '4000MHz',
            'CAS Latency': '19',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Kingston HyperX Fury 16GB (2 x 8GB) DDR4 2666MHz',
          category_id: 3,
          price: 5500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/KingstonHyperXFury.jpg',
          description: JSON.stringify({
            Capacity: '16GB (2 x 8GB)',
            'Memory Type': 'DDR4',
            Speed: '2666MHz',
            'CAS Latency': '16',
            Voltage: '1.2V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Team T-Force Vulcan Z 32GB (2 x 16GB) DDR4 3000MHz',
          category_id: 3,
          price: 8000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/TeamT-ForceVulcanZ32GB.jpg',
          description: JSON.stringify({
            Capacity: '32GB (2 x 16GB)',
            'Memory Type': 'DDR4',
            Speed: '3000MHz',
            'CAS Latency': '16',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Corsair Vengeance LPX 16GB (2 x 8GB) DDR4 3200MHz',
          category_id: 3,
          price: 7500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/corsair-vengeance-lpx-16gb-2x8gb-ddr4-3200mhz.jpg',
          description: JSON.stringify({
            Capacity: '16GB (2 x 8GB)',
            'Memory Type': 'DDR4',
            Speed: '3200MHz',
            'CAS Latency': '16',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'G.Skill Trident Z RGB 32GB (2 x 16GB) DDR4 3600MHz',
          category_id: 3,
          price: 10500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/G.SkillTridentZRGB32GB.jpg',
          description: JSON.stringify({
            Capacity: '32GB (2 x 16GB)',
            'Memory Type': 'DDR4',
            Speed: '3600MHz',
            'CAS Latency': '18',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Crucial Ballistix 16GB (2 x 8GB) DDR4 3000MHz',
          category_id: 3,
          price: 6000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/CrucialBallistix16GB.jpg',
          description: JSON.stringify({
            Capacity: '16GB (2 x 8GB)',
            'Memory Type': 'DDR4',
            Speed: '3000MHz',
            'CAS Latency': '15',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Kingston HyperX Fury RGB 16GB (2 x 8GB) DDR4 3200MHz',
          category_id: 3,
          price: 6500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/KingstonHyperXFuryRGB16GB.jpg',
          description: JSON.stringify({
            Capacity: '16GB (2 x 8GB)',
            'Memory Type': 'DDR4',
            Speed: '3200MHz',
            'CAS Latency': '16',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Team T-Force Delta RGB 32GB (2 x 16GB) DDR4 3200MHz',
          category_id: 3,
          price: 8500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/TeamT-ForceDeltaRGB32GB.jpg',
          description: JSON.stringify({
            Capacity: '32GB (2 x 16GB)',
            'Memory Type': 'DDR4',
            Speed: '3200MHz',
            'CAS Latency': '16',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Corsair Vengeance RGB Pro 32GB (2 x 16GB) DDR4 3600MHz',
          category_id: 3,
          price: 9500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/CorsairVengeanceRGBPro32GB.jpg',
          description: JSON.stringify({
            Capacity: '32GB (2 x 16GB)',
            'Memory Type': 'DDR4',
            Speed: '3600MHz',
            'CAS Latency': '18',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'G.Skill Ripjaws V 16GB (2 x 8GB) DDR4 3200MHz',
          category_id: 3,
          price: 7000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/G.SkillRipjawsV16GB.jpg',
          description: JSON.stringify({
            Capacity: '16GB (2 x 8GB)',
            'Memory Type': 'DDR4',
            Speed: '3200MHz',
            'CAS Latency': '16',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Crucial Ballistix MAX 32GB (2 x 16GB) DDR4 4000MHz',
          category_id: 3,
          price: 11000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/crucial-ballistix-mae02b1f6530401a5e1420.jpg.png',
          description: JSON.stringify({
            Capacity: '32GB (2 x 16GB)',
            'Memory Type': 'DDR4',
            Speed: '4000MHz',
            'CAS Latency': '19',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Kingston HyperX Fury 16GB (2 x 8GB) DDR4 2666MHz',
          category_id: 3,
          price: 5500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/KingstonHyperXFury16GB.jpg.webp',
          description: JSON.stringify({
            Capacity: '16GB (2 x 8GB)',
            'Memory Type': 'DDR4',
            Speed: '2666MHz',
            'CAS Latency': '16',
            Voltage: '1.2V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Team T-Force Vulcan Z 32GB (2 x 16GB) DDR4 3200MHz',
          category_id: 3,
          price: 8000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/TeamT-ForceVulcanZ32GB.webp',
          description: JSON.stringify({
            Capacity: '32GB (2 x 16GB)',
            'Memory Type': 'DDR4',
            Speed: '3200MHz',
            'CAS Latency': '16',
            Voltage: '1.35V',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          category_id: 4,
          name: 'SSD Kingston A2000',
          price: 5000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/SSDKingstonA2000.jpg',
          description: JSON.stringify({
            capacity: '500GB',
            interface: 'NVMe PCIe M.2',
            form_factor: 'M.2 2280',
            speed: 'Read up to 2200MB/s, Write up to 2000MB/s',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          category_id: 4,
          name: 'HDD Seagate Barracuda',
          price: 4000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/BarraCuda2TB-large.jpg',
          description: JSON.stringify({
            capacity: '2TB',
            interface: 'SATA 6Gb/s',
            form_factor: '3.5-inch',
            speed: '7200 RPM',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          category_id: 4,
          name: 'SSD Samsung 970 EVO Plus',
          price: 8000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/SSDSamsung970EVOPlus.jpg',
          description: JSON.stringify({
            capacity: '1TB',
            interface: 'NVMe PCIe M.2',
            form_factor: 'M.2 2280',
            speed: 'Read up to 3500MB/s, Write up to 3300MB/s',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          category_id: 4,
          name: 'HDD Western Digital Blue',
          price: 3500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/HDDWesternDigitalBlue.jpg',
          description: JSON.stringify({
            capacity: '1TB',
            interface: 'SATA 6Gb/s',
            form_factor: '3.5-inch',
            speed: '5400 RPM',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          category_id: 4,
          name: 'SSD Crucial MX500',
          price: 4500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/SSDCrucialMX500.jpeg',
          description: JSON.stringify({
            capacity: '1TB',
            interface: 'SATA 6Gb/s',
            form_factor: '2.5-inch',
            speed: 'Read up to 560MB/s, Write up to 510MB/s',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          category_id: 4,
          name: 'SSD WD Blue SN550',
          price: 6000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/SSDWDBlueSN550.jpg',
          description: JSON.stringify({
            capacity: '500GB',
            interface: 'NVMe PCIe M.2',
            form_factor: 'M.2 2280',
            speed: 'Read up to 2400MB/s, Write up to 1750MB/s',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          category_id: 4,
          name: 'HDD Toshiba P300',
          price: 3000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/HDDToshibaP300.webp',
          description: JSON.stringify({
            capacity: '1TB',
            interface: 'SATA 6Gb/s',
            form_factor: '3.5-inch',
            speed: '7200 RPM',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          category_id: 4,
          name: 'SSD SanDisk Ultra 3D',
          price: 3500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/SSDSanDiskUltra3D.webp',
          description: JSON.stringify({
            capacity: '500GB',
            interface: 'SATA 6Gb/s',
            form_factor: '2.5-inch',
            speed: 'Read up to 560MB/s, Write up to 530MB/s',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          category_id: 4,
          name: 'HDD WD Red',
          price: 5500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/HDDWDRed.jpg',
          description: JSON.stringify({
            capacity: '4TB',
            interface: 'SATA 6Gb/s',
            form_factor: '3.5-inch',
            speed: '5400 RPM',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          category_id: 4,
          name: 'SSD Samsung 860 EVO',
          price: 7000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/SSDSamsung860EVO.jpg',
          description: JSON.stringify({
            capacity: '1TB',
            interface: 'SATA 6Gb/s',
            form_factor: '2.5-inch',
            speed: 'Read up to 550MB/s, Write up to 520MB/s',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Corsair RM750x',
          category_id: 6,
          price: 7990,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/CorsairRM750x.jpg',
          description: JSON.stringify({
            Power: '750W',
            Modularity: 'Full Modular',
            Efficiency: '80 Plus Gold',
            'Fan Size': '135mm',
            Connectors: '1 x ATX, 2 x EPS, 4 x PCIe, 8 x SATA, 8 x Molex',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'EVGA SuperNOVA 650 G3',
          category_id: 6,
          price: 6490,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/EVGASuperNOVA650G3.jpg',
          description: JSON.stringify({
            Power: '650W',
            Modularity: 'Fully Modular',
            Efficiency: '80 Plus Gold',
            'Fan Size': '130mm',
            Connectors: '1 x ATX, 2 x EPS, 4 x PCIe, 9 x SATA, 6 x Molex',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Seasonic Focus GX-850',
          category_id: 6,
          price: 10990,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/SeasonicFocusGX-850.jpg',
          description: JSON.stringify({
            Power: '850W',
            Modularity: 'Full Modular',
            Efficiency: '80 Plus Gold',
            'Fan Size': '120mm',
            Connectors: '1 x ATX, 2 x EPS, 6 x PCIe, 10 x SATA, 5 x Molex',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Thermaltake Toughpower GF1 750W',
          category_id: 6,
          price: 8590,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/ThermaltakeToughpowerGF1750W.png',
          description: JSON.stringify({
            Power: '750W',
            Modularity: 'Full Modular',
            Efficiency: '80 Plus Gold',
            'Fan Size': '140mm',
            Connectors: '1 x ATX, 2 x EPS, 4 x PCIe, 9 x SATA, 6 x Molex',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Cooler Master MWE Gold 650',
          category_id: 6,
          price: 6990,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/CoolerMasterMWEGold650.jpg',
          description: JSON.stringify({
            Power: '650W',
            Modularity: 'Semi Modular',
            Efficiency: '80 Plus Gold',
            'Fan Size': '120mm',
            Connectors: '1 x ATX, 1 x EPS, 2 x PCIe, 6 x SATA, 3 x Molex',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'be quiet! Straight Power 11 650W',
          category_id: 6,
          price: 8490,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/bequiet!StraightPower11650W.jpg',
          description: JSON.stringify({
            Power: '650W',
            Modularity: 'Full Modular',
            Efficiency: '80 Plus Gold',
            'Fan Size': '135mm',
            Connectors: '1 x ATX, 2 x EPS, 4 x PCIe, 9 x SATA, 6 x Molex',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'FSP Hydro G PRO 750W',
          category_id: 6,
          price: 7790,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/FSPHydroGPRO750W.jpg',
          description: JSON.stringify({
            Power: '750W',
            Modularity: 'Full Modular',
            Efficiency: '80 Plus Gold',
            'Fan Size': '135mm',
            Connectors: '1 x ATX, 2 x EPS, 4 x PCIe, 8 x SATA, 8 x Molex',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Antec Earthwatts Gold Pro 750W',
          category_id: 6,
          price: 7590,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/AntecEarthwattsGoldPro750W.jpg',
          description: JSON.stringify({
            Power: '750W',
            Modularity: 'Semi Modular',
            Efficiency: '80 Plus Gold',
            'Fan Size': '120mm',
            Connectors: '1 x ATX, 2 x EPS, 4 x PCIe, 8 x SATA, 6 x Molex',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Gigabyte P750GM',
          category_id: 6,
          price: 6690,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/GigabyteP750GM.webp',
          description: JSON.stringify({
            Power: '750W',
            Modularity: 'Semi Modular',
            Efficiency: '80 Plus Gold',
            'Fan Size': '120mm',
            Connectors: '1 x ATX, 2 x EPS, 4 x PCIe, 8 x SATA, 5 x Molex',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'SilverStone Strider Gold S 750W',
          category_id: 6,
          price: 8990,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/SilverStoneStriderGoldS750W.jpg',
          description: JSON.stringify({
            Power: '750W',
            Modularity: 'Full Modular',
            Efficiency: '80 Plus Gold',
            'Fan Size': '120mm',
            Connectors: '1 x ATX, 2 x EPS, 4 x PCIe, 8 x SATA, 6 x Molex',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Corsair Carbide Series 275R',
          category_id: 7,
          price: 5500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/CorsairCarbideSeries275R.jpg',
          description: JSON.stringify({
            'Form Factor': 'ATX',
            'Motherboard Compatibility': 'ATX, Micro-ATX, Mini-ITX',
            'Drive Bays': '2 x 3.5", 2 x 2.5"',
            'Expansion Slots': '7',
            'Front I/O Ports': '2 x USB 3.0, Audio In/Out',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'NZXT H510',
          category_id: 7,
          price: 4500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/NZXTH510.jpg',
          description: JSON.stringify({
            'Form Factor': 'ATX, Micro-ATX, Mini-ITX',
            'Motherboard Compatibility': 'ATX, Micro-ATX, Mini-ITX',
            'Drive Bays': '2 x 2.5", 2 x 3.5" (Removable)',
            'Expansion Slots': '7',
            'Front I/O Ports':
              '1 x USB 3.1 Gen 2 Type-C, 1 x USB 3.1 Gen 1 Type-A, 1 x USB 3.0 Type-A, 1 x Audio/Mic',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Cooler Master MasterBox Q300L',
          category_id: 7,
          price: 3000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/CoolerMasterMasterBoxQ300L.webp',
          description: JSON.stringify({
            'Form Factor': 'Micro-ATX, Mini-ITX',
            'Motherboard Compatibility': 'Micro-ATX, Mini-ITX',
            'Drive Bays': '1 x 3.5", 2 x 2.5"',
            'Expansion Slots': '4',
            'Front I/O Ports': '2 x USB 3.0, Audio In/Out',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Fractal Design Meshify C',
          category_id: 7,
          price: 6500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/FractalDesignMeshifyC.webp',
          description: JSON.stringify({
            'Form Factor': 'ATX, Micro-ATX, Mini-ITX',
            'Motherboard Compatibility': 'ATX, Micro-ATX, Mini-ITX',
            'Drive Bays': '2 x 3.5", 3 x 2.5"',
            'Expansion Slots': '7',
            'Front I/O Ports': '2 x USB 3.0, Audio In/Out',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Phanteks Eclipse P400A',
          category_id: 7,
          price: 5000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/PhanteksEclipseP400A.jpeg',
          description: JSON.stringify({
            'Form Factor': 'ATX, Micro-ATX, Mini-ITX',
            'Motherboard Compatibility': 'ATX, Micro-ATX, Mini-ITX',
            'Drive Bays': '2 x 3.5", 2 x 2.5"',
            'Expansion Slots': '7',
            'Front I/O Ports': '2 x USB 3.0, 1 x USB 3.1 Type-C, Audio In/Out',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Lian Li PC-O11 Dynamic',
          category_id: 7,
          price: 8500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/LianLiPC-O11Dynamic.jpg',
          description: JSON.stringify({
            'Form Factor': 'ATX, EATX, Micro-ATX',
            'Motherboard Compatibility': 'ATX, EATX, Micro-ATX',
            'Drive Bays': '4 x 3.5", 11 x 2.5"',
            'Expansion Slots': '8',
            'Front I/O Ports': '2 x USB 3.0, 1 x USB 3.1 Type-C, HD Audio',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Thermaltake Core P3',
          category_id: 7,
          price: 4000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/ThermaltakeCoreP3.jpg',
          description: JSON.stringify({
            'Form Factor': 'ATX, Micro-ATX, Mini-ITX',
            'Motherboard Compatibility': 'ATX, Micro-ATX, Mini-ITX',
            'Drive Bays': '2 x 3.5", 3 x 2.5"',
            'Expansion Slots': '8',
            'Front I/O Ports': '2 x USB 3.0, 2 x USB 2.0, HD Audio',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'be quiet! Pure Base 500DX',
          category_id: 7,
          price: 6000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/bequiet!PureBase500DX.png',
          description: JSON.stringify({
            'Form Factor': 'ATX, Micro-ATX, Mini-ITX',
            'Motherboard Compatibility': 'ATX, Micro-ATX, Mini-ITX',
            'Drive Bays': '2 x 3.5", 5 x 2.5"',
            'Expansion Slots': '7',
            'Front I/O Ports':
              '1 x USB 3.1 Gen 2 Type-C, 2 x USB 3.0, HD Audio',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'SilverStone RL06',
          category_id: 7,
          price: 3500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/silverstone-rl06-featured.jpg',
          description: JSON.stringify({
            'Form Factor': 'ATX, Micro-ATX',
            'Motherboard Compatibility': 'ATX, Micro-ATX',
            'Drive Bays': '3 x 3.5", 2 x 2.5"',
            'Expansion Slots': '7',
            'Front I/O Ports': '2 x USB 3.0, Audio In/Out',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Deepcool Matrexx 55',
          category_id: 7,
          price: 2500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/DeepcoolMatrexx55.webp',
          description: JSON.stringify({
            'Form Factor': 'ATX, Micro-ATX, Mini-ITX',
            'Motherboard Compatibility': 'ATX, Micro-ATX, Mini-ITX',
            'Drive Bays': '2 x 3.5", 4 x 2.5"',
            'Expansion Slots': '7',
            'Front I/O Ports': '2 x USB 3.0, Audio In/Out',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Noctua NH-D15',
          category_id: 8,
          price: 9200,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/NoctuaNH-D15.jpg',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel LGA2066, LGA2011-0 & LGA2011-3 (Square ILM), LGA1156, LGA1155, LGA1151, LGA1150 & AMD AM2, AM2+, AM3, AM3+, FM1, FM2, FM2+ (backplate required), AM4 with NM-AM4-UxS',
            'Fan Speed': '300 - 1500 RPM',
            Airflow: '82.5 CFM',
            'Noise Level': '24.6 dBA',
            Height: '165 mm',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'be quiet! Dark Rock Pro 4',
          category_id: 8,
          price: 7600,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/bequiet!DarkRockPro4.jpg',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel: LGA 2066 / 2011(-3) / 1366 / 115x, AMD: AM4 / AM3(+) / AM2(+) / FM2(+) / FM1',
            'Fan Speed': '600 - 1500 RPM',
            Airflow: '57.2 CFM',
            'Noise Level': '24.3 dBA',
            Height: '162.8 mm',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Cooler Master MasterLiquid ML240L RGB',
          category_id: 8,
          price: 4200,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/masterliquid-ml240l-v2-rgb-gallery-1-zoom.png',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel LGA2066, LGA2011-v3, LGA2011, LGA1200, LGA1151, LGA1150, LGA1156, LGA1155, LGA1366',
            'Fan Speed': '650 - 2000 RPM',
            Airflow: '66.7 CFM',
            'Noise Level': '6 - 30 dBA',
            Height: '157 mm',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Arctic Freezer 34 eSports DUO',
          category_id: 8,
          price: 2500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/ArcticFreezer34eSportsDUO.webp',
          description: JSON.stringify({
            'Socket Compatibility': 'Intel 115X, 2011-3, 2066, AMD AM4',
            'Fan Speed': '200 - 2100 RPM',
            Airflow: '104 CFM',
            'Noise Level': '0.3 Sone',
            Height: '157 mm',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Thermaltake Floe Riing RGB 240 TT Premium Edition',
          category_id: 8,
          price: 5300,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/ThermaltakeFloeRiingRGB240TTPremiumEdition.jpg',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel LGA 2066/2011-3/2011/1366/1156/1155/1151/1150, AMD AM4/FM2/FM1/AM3+/AM3/AM2+/AM2',
            'Fan Speed': '500 - 1400 RPM',
            Airflow: '42.45 CFM',
            'Noise Level': '24.7 dBA',
            Height: '270 mm',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Corsair H100i RGB PLATINUM SE',
          category_id: 8,
          price: 7100,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/CorsairH100iRGBPLATINUMSE.jpg',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel 1150 / 1151 / 1155 / 1156 / 1200 / 2011 / 2011-3 / 2066, AMD AM4 / AM3 / AM2',
            'Fan Speed': '2400 RPM',
            Airflow: '75 CFM',
            'Noise Level': '37 dBA',
            Height: '277 mm',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'NZXT Kraken X62',
          category_id: 8,
          price: 7800,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/svo_dlya_protsessora_nzxt_kraken_series_x62_280mm_rl_krx62_02_1.jpg',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel Socket 1151, 1150, 1155, 1156, 1366, 2011, 2011-3, 2066, AMD Socket AM4, FM2+, FM2, FM1, AM3+, AM3, AM2+, AM2',
            'Fan Speed': '500 - 2000 RPM',
            Airflow: '98.17 CFM',
            'Noise Level': '21 - 38 dBA',
            Height: '315 mm',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Deepcool GAMMAXX 400 V2',
          category_id: 8,
          price: 1500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/DeepcoolGAMMAXX400V2.webp',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel LGA1200/2066/2011-v3/2011/1151/1150/1155/1366, AMD AM4/AM3+/AM3/AM2+/AM2/FM2+/FM2/FM1',
            'Fan Speed': '500 - 1650 RPM',
            Airflow: '74.34 CFM',
            'Noise Level': '27.8 dBA',
            Height: '155 mm',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'CRYORIG H7',
          category_id: 8,
          price: 3200,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/CRYORIGH7.webp',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel LGA1156, LGA1155, LGA1151, LGA1150, AMD AM4, AM3+, AM3, AM2+, AM2, FM2+, FM2, FM1',
            'Fan Speed': '330 - 1600 RPM',
            Airflow: '49 CFM',
            'Noise Level': '25 dBA',
            Height: '145 mm',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Cooler Master Hyper 212 RGB Black Edition',
          category_id: 8,
          price: 2800,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/hyper-212-rgb-gallery-1-zoom.png',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel LGA 2066 / 2011-v3 / 2011 / 1366 / 1151 / 1150 / 1155 / 1156 / 775, AMD AM4 / AM3+ / AM3 / AM2+ / AM2 / FM2+ / FM2 / FM1',
            'Fan Speed': '650 - 2000 RPM',
            Airflow: '57.3 CFM',
            'Noise Level': '26 dBA',
            Height: '159 mm',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Corsair Hydro Series H100i RGB Platinum',
          category_id: 9,
          price: 8500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/svo_dlya_protsessora_corsair_hydro_series_h100i_rgb_platinum_240mm_cw_9060039_ww_1024665_1.jpg',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel LGA 2066/2011-v3/2011/1200/1151/1150/1155/1156/1366 and AMD AM4/AM3+/AM3/AM2+/AM2/FM2+/FM2/FM1',
            'Radiator Size': '240mm',
            'Fan Speed': '2400 RPM',
            'Noise Level': '37 dBA',
            'RGB Lighting': 'Yes',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'NZXT Kraken X62 Rev 2',
          category_id: 9,
          price: 9800,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/1139058-nzxt-kraken-x62.jpg',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel LGA 2066/2011-v3/2011/1200/1151/1150/1155/1156/1366 and AMD AM4/AM3+/AM3/AM2+/AM2/FM2+/FM2/FM1',
            'Radiator Size': '280mm',
            'Fan Speed': '500 - 1,800 RPM',
            'Noise Level': '21 - 38 dBA',
            'RGB Lighting': 'Yes',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'EVGA CLC 280',
          category_id: 9,
          price: 7600,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/EVGACLC280.png',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel LGA 2066/2011-v3/2011/1200/1151/1150/1155/1156/1366 and AMD AM4/AM3+/AM3/AM2+/AM2/FM2+/FM2/FM1',
            'Radiator Size': '280mm',
            'Fan Speed': '600 - 2200 RPM',
            'Noise Level': '16 - 39.5 dBA',
            'RGB Lighting': 'Yes',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Thermaltake Floe Riing RGB 360 TT Premium Edition',
          category_id: 9,
          price: 11000,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/ThermaltakeFloeRiingRGB360TTPremiumEdition.webp',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel LGA 2066/2011-3/2011/1366/1200/1156/1155/1151/1150 and AMD AM4/FM2/FM1/AM3+/AM3/AM2+/AM2',
            'Radiator Size': '360mm',
            'Fan Speed': '500 - 1400 RPM',
            'Noise Level': '19.8 - 24.7 dBA',
            'RGB Lighting': 'Yes',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Deepcool Captain 240EX RGB White',
          category_id: 9,
          price: 5500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/DeepcoolCaptain240EXRGB.jpg',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel LGA2066/2011-v3/2011/1151/1150/1155/1366 and AMD AM4/AM3+/AM3/AM2+/AM2/FM2+/FM2/FM1',
            'Radiator Size': '240mm',
            'Fan Speed': '500 - 1800 RPM',
            'Noise Level': '17.8 - 30 dBA',
            'RGB Lighting': 'Yes',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Cooler Master MasterLiquid ML360R RGB',
          category_id: 9,
          price: 9500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/CoolerMasterMasterLiquidML360RRGB.jpg',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel LGA 2066/2011-v3/2011/1200/1151/1150/1155/1366 and AMD AM4/AM3+/AM3/AM2+/AM2/FM2+/FM2/FM1',
            'Radiator Size': '360mm',
            'Fan Speed': '650 - 2000 RPM',
            'Noise Level': '6 - 30 dBA',
            'RGB Lighting': 'Yes',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'NZXT Kraken X53',
          category_id: 9,
          price: 5800,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/NZXTKrakenX53.webp',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel LGA 2066/2011-v3/2011/1200/1151/1150/1155/1156/1366 and AMD AM4/AM3+/AM3/AM2+/AM2/FM2+/FM2/FM1',
            'Radiator Size': '240mm',
            'Fan Speed': '500 - 2000 RPM',
            'Noise Level': '21 - 36 dBA',
            'RGB Lighting': 'Yes',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Corsair iCUE H150i ELITE CAPELLIX',
          category_id: 9,
          price: 11500,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/CorsairiCUEH150iELITECAPELLIX.png',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel LGA 1200/1150/1151/1155/1156/1366/2011/2066 and AMD AM4/AM3/AM2/FM2/FM1',
            'Radiator Size': '360mm',
            'Fan Speed': '400 - 2400 RPM',
            'Noise Level': '10 - 37 dBA',
            'RGB Lighting': 'Yes',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Thermaltake Water 3.0 ARGB 360 Sync',
          category_id: 9,
          price: 4200,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/ThermaltakeWater3.0ARGBSync.webp',
          description: JSON.stringify({
            'Socket Compatibility':
              'Intel LGA 2066/2011-3/2011/1366/1200/1156/1155/1151/1150 and AMD AM4/FM2/FM1/AM3+/AM3/AM2+/AM2',
            'Radiator Size': '240mm',
            'Fan Speed': '500 - 1500 RPM',
            'Noise Level': '25 dBA',
            'RGB Lighting': 'Yes',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Creative Sound Blaster Z',
          category_id: 10,
          price: 5890,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/CreativeSoundBlasterZ.webp',
          description: JSON.stringify({
            Channels: '5.1',
            'Signal-to-Noise Ratio (SNR)': '116 dB',
            'Max Sample Rate': '192 kHz',
            Interface: 'PCI Express',
            'Audio Processor': 'Sound Core3D',
            'DAC (Digital-to-Analog Converter)': '24-bit/192 kHz',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'ASUS Xonar Essence STX II',
          category_id: 10,
          price: 12990,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/ASUSXonarEssenceSTXII.jpg',
          description: JSON.stringify({
            Channels: '7.1',
            'Signal-to-Noise Ratio (SNR)': '124 dB',
            'Max Sample Rate': '192 kHz',
            Interface: 'PCI Express',
            'Audio Processor': 'ASUS AV100',
            'DAC (Digital-to-Analog Converter)': '24-bit/192 kHz',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Focusrite Scarlett 2i2',
          category_id: 10,
          price: 7990,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/FocusriteScarlett2i2.jpg',
          description: JSON.stringify({
            Channels: '2',
            'Max Sample Rate': '192 kHz',
            Interface: 'USB',
            'Bit Depth': '24-bit',
            'DAC (Digital-to-Analog Converter)': '24-bit/192 kHz',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'M-Audio AIR 192|4',
          category_id: 10,
          price: 4990,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/M-AudioAIR1924.jpg',
          description: JSON.stringify({
            Channels: '2',
            'Max Sample Rate': '192 kHz',
            Interface: 'USB',
            'Bit Depth': '24-bit',
            'DAC (Digital-to-Analog Converter)': '24-bit/192 kHz',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Behringer U-Phoria UM2',
          category_id: 10,
          price: 2490,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/BehringerU-PhoriaUM2.jpg',
          description: JSON.stringify({
            Channels: '2',
            'Max Sample Rate': '48 kHz',
            Interface: 'USB',
            'Bit Depth': '16-bit',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'ESI MAYA44 USB+',
          category_id: 10,
          price: 6990,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/ESIMAYA44USB+.jpg',
          description: JSON.stringify({
            Channels: '4',
            'Max Sample Rate': '48 kHz',
            Interface: 'USB',
            'Bit Depth': '24-bit',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Roland UA-1010 Octa-Capture',
          category_id: 10,
          price: 29990,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/RolandUA-1010Octa-Capture.jpg',
          description: JSON.stringify({
            Channels: '10',
            'Max Sample Rate': '192 kHz',
            Interface: 'USB',
            'Bit Depth': '24-bit',
            'DAC (Digital-to-Analog Converter)': '24-bit/192 kHz',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'RME Fireface UC',
          category_id: 10,
          price: 35990,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/RMEFirefaceUCX.jpg',
          description: JSON.stringify({
            Channels: '36',
            'Max Sample Rate': '192 kHz',
            Interface: 'USB',
            'Bit Depth': '24-bit',
            'DAC (Digital-to-Analog Converter)': '24-bit/192 kHz',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Presonus AudioBox USB 96',
          category_id: 10,
          price: 3590,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/presonus_audiobox_96_studio_0.png.webp',
          description: JSON.stringify({
            Channels: '2',
            'Max Sample Rate': '96 kHz',
            Interface: 'USB',
            'Bit Depth': '24-bit',
          }),
          createdAt: faker.date.anytime(),
        },
        {
          name: 'Steinberg UR22mkII',
          category_id: 10,
          price: 6990,
          order_count: randomOrderCount(),
          img: 'http://localhost:3000/images/steinberg_ur22_mkii1.jpg',
          description: JSON.stringify({
            Channels: '2',
            'Max Sample Rate': '192 kHz',
            Interface: 'USB',
            'Bit Depth': '24-bit',
            'DAC (Digital-to-Analog Converter)': '24-bit/192 kHz',
          }),
          createdAt: faker.date.anytime(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Items', null, {});
  },
};
